### ISSUE TITLE
UIP-3221 react.js and react_dom.js must be loaded. Error after follow Readme

### ISSUE THREAD

**Issue by francisl** [Workiva/over_react#148]
> * Issue Type: [BUG?, DOCUMENTATION]
> * `over_react` Version(s): `1.23.0`

I want to get started with over_react but following the instruction on the readme lead to an error I cannot solve as a Dart beginners.

Here the steps I follow
1. Install Dart 2 with brew on Mac OS
2. Install Intellij Dart and flutter plugin
3. I create a basic web project in intellij (not angular)
4. Follow the steps in the README (after step 2 I did `pub get`

This is the error I have :
```
react_interop.dart:32 Uncaught ReferenceError: render is not defined
    at StaticClosure.dart.ReactDom_render (react_interop.dart:32)
    at StaticClosure.dart.main (main.dart:56)
    at _IsolateContext.eval$1 (isolate_helper.dart:475)
    at Object.startRootIsolate (isolate_helper.dart:130)
```

I though it could be that I have to manual add the dependencies. But still no luck.

Here is a repo of the code I have after these steps https://github.com/francisl/test_over_react

---

> __FYI:__ @greglittlefield-wf @aaronlademann-wf @jacehensley-wf @clairesarsam-wf @joelleibow-wf

**Comment by rmconsole2-wf** [comment]
It looks like you have not included any tickets in the title of this issue. Please create a ticket for this issue, or click a type to create one automatically: <a href="https://w-rmconsole.appspot.com/api/v1/issues/Workiva/over_react/148/addTicketToTitle/Task/">Task</a>, <a href="https://w-rmconsole.appspot.com/api/v1/issues/Workiva/over_react/148/addTicketToTitle/Bug/">Bug</a>, <a href="https://w-rmconsole.appspot.com/api/v1/issues/Workiva/over_react/148/addTicketToTitle/Improvement/">Improvement</a>

**Comment by aaronlademann-wf** [comment]
Hi @francisl! Thanks for trying it out!

I've opened https://github.com/francisl/test_over_react/pull/1 to fix your example.

The problem was that you had your component definition in a file within `web/`. The `over_react` transformer does not run in web/ by default, which is what caused your issue.

Let us know if you have any more issues!

**Comment by francisl** [comment]
@aaronerickson-wf Thanks for the PR and information.

One other problem I had, was that I was running dart 2. Is there a branch of over_react that works with dart 2?

Thanks again
