### ISSUE TITLE
Error while running tests -  Unable to spawn isolate: The built-in library 'dart:html' is not available on the stand-alone VM. 

### ISSUE THREAD

**Issue by arun-sahadevan** [Workiva/over_react#160]
> * Issue Type: BUG,
> * `over_react` Version(s): `1.18.1`

Hi i ran into this issue while running test for the first time on cloning the git repo . i didnt make any changes . Even then on running the tests as mentioned in documentation , wm getting error like 

  _Unable to spawn isolate: The built-in library 'dart:html' is not available on the stand-alone VM.
 'package:todo_dart_react/src/todo_dart_react/components.dart': error: line 5 pos 1: library handler failed
  import 'dart:html';_

What might be the possible reason?. i tried for some solutions . But not working
![capture4](https://user-images.githubusercontent.com/39547347/41769919-6690a746-762e-11e8-8dd6-61aeb1e0045c.PNG)

**Comment by arun-sahadevan** [comment]
@johncblandii @mikewesner-wf @davetucker-wf @codebuilders-wf @matthewbalvanz-wf  . Can anyone please help ?

**Comment by matthewbalvanz-wf** [comment]
FYI: @greglittlefield-wf @aaronlademann-wf

I'm not sure the group originally mentioned has a lot of experience with this project. Would you guys be able to take a look at this issue?

**Comment by johncblandii** [comment]
@arun-sahadevan it looks like you're running a VM test: https://github.com/leerob/dart-react-todo/blob/master/test/unit/todo_dart_react/stores/todo_store_test.dart.

Run the [entire suite](https://github.com/leerob/dart-react-todo/blob/master/test/unit/generated_runner_test.dart) and see if the same error happens.

**Comment by arun-sahadevan** [comment]
Thanks @matthewbalvanz-wf  and @johncblandii  . 

I tried running the entire test suite by command :  
`
pub run test --pub-serve=8081 test/unit/generated_runner_test.dart`
 Not getting any error , but showing no tests ran . 

![capture5](https://user-images.githubusercontent.com/39547347/41890247-42350850-792c-11e8-9c88-e1e7a0f3ffa6.PNG)

generated_runner_test.dart contains references to all other test files . Even then not able to run  any test . 
I guess the command i used is correct . Please correct me if am wrong .

**Comment by johncblandii** [comment]
Are you starting a pub instance om port 8081?

You should try using `dart_dev`. It is already included so you can just run `pub run dart_dev` and not sweat the rest of that line. It will automatically start a pub instance and use it for the tests. You can see ddev will open it content-shell in this case.

```
~/Work/opensource/dart-react-todo (master): pub run dart_dev test

::: pub serve --port=0 test
    Loading source assets...
    Loading over_react and test/pub_serve transformers...
    Serving todo_dart_react test on http://localhost:65089

::: pub run test --concurrency=4 -p content-shell --reporter=expanded --pub-serve=65089 test/unit/generated_runner_test.dart
```

I also ran all over_react tests with no problem and this computer didn't have Dart on it at all prior to 10 minutes ago. It seems your issues are with the commands, set up, or tests and in a separate repo.

Feel free to post your code if you're not using [dart-react-todo](https://github.com/leerob/dart-react-todo#testing) as your source or open an issue on that repo and tag me. I'll help there as well.

**Comment by arun-sahadevan** [comment]
Are you using Mac system . Am running on a windows machine @johncblandii

**Comment by johncblandii** [comment]
Yup, I'm on a Mac. It is the only way to roll. ;)

**Comment by aaronlademann-wf** [comment]
@arun-sahadevan you can't run tests in the VM when importing a browser-only library like `dart:html`.

When running your test(s), you need to use the `-p` flag to specify something like "chrome".

The other thing is, unless you have a standalone `.html` file that accompanies the test file you're referencing when you run the test command, you can't test it in a browser.

I'd recommend using the `pub run dart_dev test` command like @johncblandii suggested like so:

```
pub run dart_dev test -p chrome
```

or 

```
pub run dart_dev test -p content-shell
```
