### ISSUE TITLE
How can we show or hide components inside OverReact according to conditions?

### ISSUE THREAD

**Issue by arun-sahadevan** [Workiva/over_react#163]
I have listed my issue in stackoverflow. Please give some suggestions regarding that.

https://stackoverflow.com/questions/51065760/how-can-we-show-or-hide-components-inside-overreact-library-to-build-react-comp

**Comment by arun-sahadevan** [comment]
I tried to show component according to condition like how it is done in react redux  . But ended up in error . i tried showing the text 'Error Occured' when hasError property is true . But even on setting it to true , the error message is not getting printed . Any idea on how such conditions can be provided in overreact for rendering specific components?


`@override
  render() {
    return Dom.div()(
        (LoginInput()
          ..addTestId('loginEmailField')
          ..fieldId = props.email
          )(),
(props.hasError) ? Dom.div()('Error occured') : null)}`

**Comment by aaronlademann-wf** [comment]
@arun-sahadevan it should be pretty straightforward...

```dart
@Component()
class YourComponent extends UiComponent<YourProps> {
  @override
  render() {
    return Dom.div()(
      (LoginInput()
        ..addTestId('loginEmailField')
        ..fieldId = props.email
        ..id = props.id
        ..inputProps = props.inputEmailProps
      )(),
      showError(),
    );
  }

  ReactElement showError() {
    if (!props.hasError) return null;

    return Dom.div()('Error occured');
  }
}
```

**Comment by arun-sahadevan** [comment]
I tried this . Still 'Error occured' text is showing always even though props.hasError in my case is changed to false on typing some text in the text field.

**Comment by arun-sahadevan** [comment]
Got the fix myself. Thanks
