### ISSUE TITLE
How can we add custom css classes and use it in our overreact application?

### ISSUE THREAD

**Issue by arun-sahadevan** [Workiva/over_react#164]
How can we add custom css classes and use it in our overreact application?. I was able to use only default bootstrap classes. Have we got a concept of adding external css files to define our styles?

**Comment by aaronlademann-wf** [comment]
@arun-sahadevan adding CSS files would not involve OverReact.  You'd just add a `<link rel="stylesheet" href="/path/to/your/stylesheet.css">` in the `<head>`.

How were you able to use bootstrap classes? Are you talking about the example components? OverReact actually doesn't provide any UI components out of the box.

### Adding CSS classes to elements:

You simply use `props.className` to do this.

```dart
@override
render() {
  return (Dom.div()..className = 'foo')(
    // ... children ...
  );
}
```

You can also use a `ClassNameBuilder` and its [`add` method](https://www.dartdocs.org/documentation/over_react/latest/over_react/ClassNameBuilder/add.html) for easy conditional CSS classes like so:

```dart
@override
render() {
  final classes = new ClassNameBuilder()
    ..add('foo')
    ..add('bar', /* a bool condition */);

  return (Dom.div()
    ..className = classes.toClassName()
  )(
    // ... children ...
  );
}
```

#### Adding CSS classes to custom components:

To allow consumers to set `props.className` (or any other standard dom prop) on a custom component, your component must [forward unconsumed props](https://www.dartdocs.org/documentation/over_react/latest/over_react.component_base/UiComponent/copyUnconsumedProps.html) / [unconsumed dom props](https://www.dartdocs.org/documentation/over_react/latest/over_react.component_base/UiComponent/copyUnconsumedDomProps.html) like so:

```dart
// If your component renders a `Dom` element
@override
render() {
  return (Dom.div()
    ..addProps(copyUnconsumedDomProps())
  )(
    props.children,
  );
}

// If your component renders another custom component
@override
render() {
  return (AnotherCustomComponent()
    ..addProps(copyUnconsumedProps())
  )(
    props.children,
  );
}
```

When you do this, and `props.className` is set on your custom component - it will be "forwarded" to the `Dom.div` / `AnotherCustomComponent`, respectively.

##### Defining custom CSS classes within your custom component

If you want to define custom CSS classes on the root node rendered by your custom component, but you also want consumers to be able to add their own CSS classes, use a special variation of a `ClassNameBuilder` called [`forwardingClassNameBuilder`](https://www.dartdocs.org/documentation/over_react/latest/over_react.component_base/UiComponent/forwardingClassNameBuilder.html):

```dart
@Factory()
UiFactory<WidgetProps> Widget;

@Props()
class WidgetProps extends UiProps {
  bool isBar;
}

@Component()
class YourComponent extends UiComponent<YourProps> {
  @override
  getDefaultProps() => (newProps()
    ..isBar = false
  );

  @override
  render() {
    final classes = forwardingClassNameBuilder()
      ..add('foo')
      ..add('bar', props.isBar);

    return (Dom.div()
      ..addProps(copyUnconsumedDomProps())
      ..className = classes.toClassName()
    )(
      props.children
    );
  }
}
```

The component above, when consumed like so:

```dart
@override
render() {
  return (Widget()
    ..isBar = true
    ..className = 'custom-class another-custom-class'
  )('hi there');
}
```

Will produce the following HTML:

```html
<div class="foo bar custom-class another-custom-class">hi there</div>
```

**Comment by arun-sahadevan** [comment]
Thank you @aaronlademann-wf  for the detailed description. Its working fine .
