### ISSUE TITLE
Accessing createClass via the main React package is deprecated, and will be removed in React v16.0

### ISSUE THREAD

**Issue by patarapolw** [Workiva/over_react#217]
> * Issue Type: BUG
> * `over_react` Version(s): `1.29.0`
> * SDK: `1.24.3`

> Warning: Accessing createClass via the main React package is deprecated, and will be removed in React v16.0. Use a plain JavaScript class instead. If you're not yet ready to migrate, create-react-class v15.* is available on npm as a temporary, drop-in replacement. For more info see https://fb.me/react-create-class

It seems that [react-dart](https://github.com/cleandart/react-dart) for Dart 2.1.0 doesn't have this issue. But I dropped back to 1.24.3 for many good plugins. Thanks for your hard work.

**Comment by aaronlademann-wf** [comment]
@patarapolw that warning is generated because of react-dart's use of React JS' `createClass` method.

That will go away once we update react-dart to utilize React JS v16.
