### ISSUE TITLE
React.js tutorial in Dart version

### ISSUE THREAD

**Issue by patarapolw** [Workiva/over_react#218]
> * Issue Type: Suggestion
> * `over_react` Version(s): `1.29.0`

[React.js tutorial](https://reactjs.org/tutorial/tutorial.html) in Dart version is here -- https://github.com/patarapolw/SimpleDart2Js#overreact-for-dart-1

I create both for React-Dart and OverReact.

I do this because I just don't want to use JavaScript/TypeScript and NPM/Yarn directly.

**Comment by aaronlademann-wf** [comment]
Very nice!
