### ISSUE TITLE
Using react-bootstrap components with over_react?

### ISSUE THREAD

**Issue by ayushin** [Workiva/over_react#235]
Hi,

First of all this seem to be like a really great initiative! Great job especially with supporting dart2 now.

My question is there an easy way of using reactstrap components with over_react?

**Comment by aaronlademann-wf** [comment]
@ayushin you would essentially need to recreate the components in Dart using over_react.

We've done a few, for example purposes - here: https://github.com/Workiva/over_react/tree/master/web/src/demo_components
