### ISSUE TITLE
UIP-1655 Dom.foreignObject doesn't exist

### ISSUE THREAD

**Issue by kasperpeulen** [Workiva/over_react#27]
> * Issue Type: [BUG]
> * `over_react` Version(s): `1.2.0`

The `foreignObject` svg tag doesn't seem to be available in over-react. Typing `dom.foreign` doesn't give any completion.

Great lib btw!

> __FYI:__ @greglittlefield-wf @aaronlademann-wf @jacehensley-wf @clairesarsam-wf @joelleibow-wf

**Comment by rmconsole3-wf** [comment]
It looks like you have not included any tickets in the title of this issue. Please create a ticket for this issue, or click <a href='https://w-rmconsole.appspot.com/api/v1/issues/Workiva/over_react/27/addTicketToTitle'>here</a> to have Rosie create one for you.

**Comment by greglittlefield-wf** [comment]
Thanks for catching this! Sorry about that.

We'll go through and make sure all the supported elements/attributes in React are available.

In the meantime, you can work around the issue with the following:
```dart
import 'package:over_react/over_react.dart';
import 'package:react/react_client.dart';

final _foreignObject = new ReactDomComponentFactoryProxy('foreignObject')
SvgProps foreign() => new SvgProps(_foreignObject);
```
