### ISSUE TITLE
UIP-1706 event store

### ISSUE THREAD

**Issue by joeblew99** [Workiva/over_react#30]
I dont see an event store here.
There are 2 or 3 in dart we can use.

also immutable types will be needed i feel.
https://github.com/jonahwilliams/immutable-dart

**Comment by rmconsole2-wf** [comment]
It looks like you have not included any tickets in the title of this issue. Please create a ticket for this issue, or click <a href='https://w-rmconsole.appspot.com/api/v1/issues/Workiva/over_react/30/addTicketToTitle'>here</a> to have Rosie create one for you.

**Comment by greglittlefield-wf** [comment]
I don't quite follow what you mean by "event store", but do you mean something like [w_flux](https://github.com/Workiva/w_flux)? If so, we provide [FluxUiComponent](https://github.com/Workiva/over_react/blob/master/lib/src/component_declaration/flux_component.dart) + friends to make integrating w_flux into your components a bit easier.

over_react is meant to just be a layer on top of React, so we'd like to preserve the notion of "just the V in MVC" and stay unopinionated about how data and events are managed in the application.

That being said, we're think libraries like w_flux and Immutable.dart are super cool, and are happy to advertise using them together with over_react!

**Comment by joeblew99** [comment]
you nailed it - thats exactly what i meant.

Are you guys going to make examples using the dart immutable and flux libs ? It woudl help me to see a working example. 

Here is another flux for art with example for instance:
https://github.com/alexeieleusis/greencat/tree/master/examples

**Comment by greglittlefield-wf** [comment]
We do have plans for doing a TodoMVC example app with over_react and w_flux (see https://github.com/Workiva/over_react/issues/24); I'm really excited for that, since I know how valuable end-to-end examples are.

A project using Immutable.dart would also be really cool to see, but we don't have any plans as of yet to build one. I'll have to play around with that lib...

**Comment by joeblew99** [comment]
Ok cheers. I guess its watch this space then :)

Will close...
