### ISSUE TITLE
UIP-1812 Community / Mailing List / Newsgroup / gitter / irc channel ?

### ISSUE THREAD

**Issue by jtrunick** [Workiva/over_react#32]
This project looks great, but I don't see anywhere to communicate with OverReact users.

Anything?

**Comment by rm-astro-wf** [comment]
It looks like you have not included any tickets in the title of this issue. Please create a ticket for this issue, or click <a href='https://w-rmconsole.appspot.com/api/v1/issues/Workiva/over_react/32/addTicketToTitle'>here</a> to have Rosie create one for you.

**Comment by greglittlefield-wf** [comment]
@jtrunick We don't currently have any kind of communication channel like that, but that's a great idea!

I'll see if we can get something set up!
