### ISSUE TITLE
Could give more examples?

### ISSUE THREAD

**Issue by steven11329** [Workiva/over_react#332]
Could give more examples.

I hope could see following examples:

- Update states
- Update states to update sub component props
- Ref operation
- event handler ( e.g. onClick )

I have no ideal how to use over_react in real world.

I'm sorry for my bad English.

**Comment by aaronlademann-wf** [comment]
Hi @steven11329 - you can see the source code for an example that uses state and props here: https://github.com/Workiva/over_react/blob/master/web/src/demo_components/toggle_button.dart
