### ISSUE TITLE
Component API access 

### ISSUE THREAD

**Issue by ppanconi** [Workiva/over_react#343]
> * Issue Type: [FEATURE REQUEST, etc.]
> * `over_react` Version(s): `2.5.2`

I'm asking if is it possible to access the Component  specific API after creating builder and element

---

> __FYI:__ @greglittlefield-wf @aaronlademann-wf @kealjones-wk @evanweible-wf @maxwellpeterson-wf

**Comment by greglittlefield-wf** [comment]
Sorry we don't have this documented, but it is possible using [callback refs](https://reactjs.org/docs/refs-and-the-dom.html#callback-refs).

For example:
```dart
class FooComponent ... {
  ...
  bar() => 'bar';
}
```
```dart
FooComponent fooRef;

render() {
  (Foo()
    ..ref = ((ref) => fooRef = ref);
  )();
}

componentDidMount() {
  print(fooRef.bar());
}
```

**Comment by ppanconi** [comment]
Good great job
Thanks
