### ISSUE TITLE
UIP-2117 Run JS unit tests in Travis

### ISSUE THREAD

**Issue by greglittlefield-wf** [Workiva/over_react#36]
Travis is slow enough that the loading of our JS unit test suites times out the test package. See dart-lang/test/issues/390

For now, we can run the tests on our private CI, but it would be great to have those results available publicly.

As an alternative solution, we could also run them on Sauce Labs.

**Comment by rm-astro-wf** [comment]
It looks like you have not included any tickets in the title of this issue. Please create a ticket for this issue, or click <a href='https://w-rmconsole.appspot.com/api/v1/issues/Workiva/over_react/36/addTicketToTitle'>here</a> to have Rosie create one for you.

**Comment by aaronlademann-wf** [comment]
This is happening in the 2.0.0 release!
