### ISSUE TITLE
Flutter-like?

### ISSUE THREAD

**Issue by jtrunick** [Workiva/over_react#41]
Curious if there is a way to wrapper or make the API a practical drop-in for flutter api?

**Comment by rm-astro-wf** [comment]
It looks like you have not included any tickets in the title of this issue. Please create a ticket for this issue, or click <a href='https://w-rmconsole.appspot.com/api/v1/issues/Workiva/over_react/41/addTicketToTitle'>here</a> to have Rosie create one for you.

**Comment by greglittlefield-wf** [comment]
Hm, not sure what you're asking here.

Flutter and its APIs are for building native apps, whereas this library is web-specific and pretty much 1:1 with React DOM functionality.

It's possible that, eventually, OverReact will be able to wrap server-side React and React Native, but there are no plans to do so as of yet.

It's also possible that, as Flutter matures, we'll take more inspiration from their APIs.

For the time being, however, Flutter and OverReact aren't really interoperable.

**Comment by jtrunick** [comment]
Is there any plan to wrap the Material design with OverReact?

**Comment by greglittlefield-wf** [comment]
No plans by this team, no. We're focused on maintaining OverReact itself, as well as the private projects we're responsible for.

We're more than happy to assist anyone interested in pursuing that effort, though!

**Comment by montyclt** [comment]
I think the question is about component API:

In over_react, the API is like this:

```
(Component()
  ..prop = 'Value'
(
  'child1',
  'child2'
));
```

In Flutter, the API is like this:
```
new Component(
  prop: 'Value' //named parameter
  chidren: [
    'child1',
    'child2'
  ]
);
```

I think flutter API is more clear when nesting components.

**Comment by montyclt** [comment]
As an idea, I propose mix the both API:

```
 //Calling component factory function.
Component(
  prop: 'Value' // Named parameters of props in first parenthesis.
)(
  'child1',
  'child2' // Children in the second parenthesis.
);
```

This avoid the `child` and `children` keyword and avoid the extra parenthesis that wraps the over_react API.
