### ISSUE TITLE
request to remove built_redux dependency

### ISSUE THREAD

**Issue by dave-doty** [Workiva/over_react#426]
> * Issue Type: FEATURE REQUEST
> * `over_react` Version(s): `3.1.4`

over_react depends on [built_redux](https://pub.dev/packages/built_redux), which due to versioning issues means I cannot upgrade to [built_value](https://pub.dev/packages/built_value) version 7.0.0 or later.

Assuming built_redux is not being used in some crucial way (I saw there were some experiments with supporting it in commits from last year, but I don't see any support in the the current documentation), it would be helpful to remove the dependency so that clients can use the latest version of built_value.

The [request](https://github.com/davidmarne/built_redux/issues/132) at the built_redux repo to upgrade the dependency is 3 weeks old, with no reply, so I'm not confident it will be resolved soon.

---

> __FYI:__ @greglittlefield-wf @aaronlademann-wf @kealjones-wk @evanweible-wf @maxwellpeterson-wf

**Comment by greglittlefield-wf** [comment]
Hey @dave-doty, sorry about that conflict. Unfortunately we need to support built_redux for some of our internal packages for a little while longer.

I reached out and there should be a version of built_redux released soon that fixes this: https://github.com/davidmarne/built_redux/pull/136
