### ISSUE TITLE
Stagehand template build_web_compilers conflicts with over_react

### ISSUE THREAD

**Issue by UnHumbleBen** [Workiva/over_react#429]
> * Issue Type: [DOC REQUEST]
> * `over_react` Version(s): `^3.0.0`

[Stagehand](https://pub.dev/packages/stagehand) templates come with build_web_compilers, which conflicts with over_react. This is a big gotcha for beginners and it would be nice if there was a warning in the docs about this. The fix is to change the version of build_web_compilers to ^2.0.0

---

> __FYI:__ @greglittlefield-wf @aaronlademann-wf @kealjones-wk @evanweible-wf @maxwellpeterson-wf

**Comment by greglittlefield-wf** [comment]
Hey @UnHumbleBen, I'm seeing that stagehand uses what seems like compatible build_web_compilers: https://github.com/dart-lang/stagehand/blob/master/templates/web-simple/pubspec.yaml#L15

Could you expand more on the issue?

Also, is it possible that you have an older version of stagehand installed, with outdated templates? You can upgrade and thus update those templates via `pub global activate stagehand`

**Comment by UnHumbleBen** [comment]
Sorry, I realize by Stagehand was outdated as you stated, closing issue.
