### ISSUE TITLE
Lint Error: Always Declare Return Type

### ISSUE THREAD

**Issue by UnHumbleBen** [Workiva/over_react#443]
> * Issue Type: [STYLE]
> * `over_react` Version(s): `3.1.x`

The declaration of render without a return type always gives me the [dart(always_declare_return_types) error](https://dart-lang.github.io/linter/lints/always_declare_return_types.html).

Should a type be added to be consistent with the style guide?

---

> __FYI:__ @greglittlefield-wf @aaronlademann-wf @kealjones-wk @evanweible-wf @maxwellpeterson-wf

**Comment by greglittlefield-wf** [comment]
Hey @UnHumbleBen, sorry that our templates/examples don't respect that lint. I've filed a issue with the linter package: https://github.com/dart-lang/linter/issues/1901, and based on how that goes, we can update things on our end.

In the mean time, I would recommend typing the return value of render as `dynamic`. 

You could type it as something more specific, but it wouldn't provide much additional static safety, and it could be annoying during development if you change your render to return something of a different type.
