### ISSUE TITLE
redux 4.0.0 incompatible with over_react ^3.1.0

### ISSUE THREAD

**Issue by UnHumbleBen** [Workiva/over_react#448]
> * Issue Type: [FEATURE REQUEST]
> * `over_react` Version(s): `^3.1.0`

Would be nice if I could use OverReact ^3.1.0 features such as UiComponent2 with [Redux](https://pub.dev/packages/redux).

---

> __FYI:__ @greglittlefield-wf @aaronlademann-wf @kealjones-wk @evanweible-wf @maxwellpeterson-wf

**Comment by aaronlademann-wf** [comment]
@UnHumbleBen version 3.4.1 has been released with compatibility for redux 4.x!
