### ISSUE TITLE
prevProps do not have generated getters

### ISSUE THREAD

**Issue by UnHumbleBen** [Workiva/over_react#449]
> * Issue Type: [FEATURE REQUEST]
> * `over_react` Version(s): `^3.1.0`

For implementing functions such as `componentDidUpdate` and `getSnapshotBeforeUpdate` and any function that has the parameter `prevProps`, is there a way to generate getters similar to how getters are generated for `UiProps`? Currently, my approach to working with `prevProps` is as follows. Supposed I have a prop:

```dart
@Props()
class _$AppProps extends UiProps with ConnectPropsMixin {
  String field;
}
```

Now suppose I try to implement `componentDidUpdate` and I want to compare the previous prop's field to the current prop's field:
```dart
  @override
  void componentDidUpdate(Map prevProps, Map prevState, [snapshot]) {
    if (props.field != prevProps['AppProps.field']) {
        // -- snip --
    }
  }
```
I am forced to use a string literal for the `prevProps` map. Is there a better way to do this? Using these string fields was exactly the kind of problem that OverReact was designed to avoid no?

---

> __FYI:__ @greglittlefield-wf @aaronlademann-wf @kealjones-wk @evanweible-wf @maxwellpeterson-wf

**Comment by maxwellpeterson-wf** [comment]
Hi @UnHumbleBen!

Check out the documentation [here](https://github.com/Workiva/over_react#accessing-and-manipulating-props--state-within-uicomponent), and look for the part about `typedPropsFactory`

**Comment by UnHumbleBen** [comment]
Silly me for missing it. Thanks!
