### ISSUE TITLE
UIP-2024 Support covariant props

### ISSUE THREAD

**Issue by greglittlefield-wf** [Workiva/over_react#49]
Dart 1.22 recently added support for [covariant overrides](https://github.com/dart-lang/sdk/blob/master/docs/language/informal/covariant-overrides.md#the-covariant-override-feature), which allows for sound tightening of method argument types.

This applies to fields/setters as well.

Currently, you cannot tighten the type of a prop in strong mode.
```dart
class FooProps {
  Iterable items;
}

class BarProps extends FooProps {
  @override
  List items; // Error: Field declaration FooProps.items cannot be overridden in BarProps.
}
```
However, with `covariant`, that should now be possible:
```dart
class FooProps {
  covariant Iterable items;
}

class BarProps extends FooProps {
  @override
  List items;
}
```

The transformer needs to be updated to generate setters with the `covariant` keyword when necessary.
```diff
-covariant Iterable items;
+Iterable get items => props[...];
+set items(covariant Iterable value) => props[...] = value;
```

Also worth noting:
> In cases where the supertype authors did not foresee this need, it is still possible to tighten a parameter type by putting the covariant modifier on the _overriding_ parameter declaration.

**Comment by rmconsole-wf** [comment]
It looks like you have not included any tickets in the title of this issue. Please create a ticket for this issue, or click <a href='https://w-rmconsole.appspot.com/api/v1/issues/Workiva/over_react/49/addTicketToTitle'>here</a> to have Rosie create one for you.
