### ISSUE TITLE
Remove cascade parens when removing last prop in assists/fixes

### ISSUE THREAD

**Issue by aaronlademann-wf** [Workiva/over_react#545]
For fixes/assists that remove props, instead of:
```diff
-(Dom.div()..key = 'foo')()
+(Dom.div())()
```

it would be nice to remove the extra parentheses:
```diff
-(Dom.div()..key = 'foo')()
+Dom.div()()
```

This could be implemented as a shared change builder, similar to `addProp`.

**Comment by greglittlefield-wf** [comment]
Fixed by #583
