### ISSUE TITLE
UIP-2153 Transition warning sometimes fires when it shouldn't

### ISSUE THREAD

**Issue by greglittlefield-wf** [Workiva/over_react#57]
> * Issue Type: BUG
> * `over_react` Version(s): `1.8.0`

The newly-added transition warning,
> VALIDATION WARNING: The number of transitions expected to complete have not completed. Something is most likely wrong.

fires when shouldn't sometimes.

For instance, sometimes transitionend events never fire on purpose, such as when the user cancels the transition (think hiding a popover while it's still showing). This results in a warning when it should not.

I also noticed in the code that the timer does not unsubscribe the listener function, which it probably should.

---

> __FYI:__ @greglittlefield-wf @aaronlademann-wf @jacehensley-wf @clairesarsam-wf @joelleibow-wf @kaanaksoy-wk

**Comment by rmconsole-wf** [comment]
It looks like you have not included any tickets in the title of this issue. Please create a ticket for this issue, or click <a href='https://w-rmconsole.appspot.com/api/v1/issues/Workiva/over_react/57/addTicketToTitle'>here</a> to have Rosie create one for you.

**Comment by gavinmulligan-wf** [comment]
@greglittlefield-wf @aaronlademann-wf I can verify we've seen this already a few times since upgrading our dependencies in `w_filing`.
